import React, { useState } from 'react';
import HomeHeader from '../../components/Header/HomeHeader';
import DashboardHeader from '../../components/Header/DashboardHeader';
import HomeFooter from '../../components/Footer/HomeFooter';
import './PublicPages.css';

function ATMBranchLocator() {
    const [openDropdown, setOpenDropdown] = useState(null);

    // Check if user is logged in by verifying if a token exists
    const isLoggedIn = !!localStorage.getItem('jwtToken');

    const queries = [
        {
            question: 'Where is the nearest bank branch or ATM?',
            answers: [
                'Use the "Branch & ATM Locator" on our website for real-time locations.',
                'Enable location services on your mobile app to find the nearest branch or ATM.',
                'You can also call customer service for the nearest branch or ATM information.',
                'The bank’s mobile app provides a map with the nearest branch and ATM locations.',
                'Some ATMs in retail stores may offer extended hours for convenience.'
            ]
        },
        {
            question: 'How do I withdraw cash without a card from an ATM?',
            answers: [
                'Use the bank’s mobile app to initiate a cardless withdrawal.',
                'Choose "Cardless Withdrawal" at the ATM and enter the code generated by the app.',
                'Follow on-screen instructions to verify your identity for secure withdrawals.',
                'Limits may apply for cardless withdrawals; check with your bank for details.',
                'Make sure to complete the transaction within the time frame provided by the bank.'
            ]
        },
        {
            question: 'What is the maximum amount I can withdraw from an ATM?',
            answers: [
                'ATM withdrawal limits vary by account type; standard accounts may have daily limits.',
                'Check your account’s terms or ask customer service for your exact withdrawal limit.',
                'Limits can also depend on ATM availability and bank policy.',
                'Higher limits are often available for premium account holders.',
                'Temporary limit increases may be possible; contact customer service for requests.'
            ]
        },
        {
            question: 'Can I deposit checks using an ATM?',
            answers: [
                'Yes, many ATMs allow check deposits if they are equipped with deposit capabilities.',
                'Insert your check and follow the on-screen instructions for a check deposit.',
                'Verify the amount displayed to ensure accuracy in the deposit.',
                'Some ATMs accept check images via the mobile app for easier deposits.',
                'Deposited checks may have a hold period before funds become available.'
            ]
        }
    ];

    const handleToggle = (index) => {
        setOpenDropdown(openDropdown === index ? null : index);
    };

    return (
        <div className="account-opening-page">
            {isLoggedIn ? <DashboardHeader /> : <HomeHeader />}
            <div className="content">
                <h1>ATM and Branch Locator</h1>
                <div className="queries">
                    {queries.map((query, index) => (
                        <div key={index} className="query-box">
                            <button
                                className="button-35"
                                onClick={() => handleToggle(index)}
                            >
                                <span>{query.question}</span>
                                <span className="arrow">{openDropdown === index ? '▲' : '▼'}</span>
                            </button>
                            {openDropdown === index && (
                                <div className="query-body">
                                    <ul>
                                        {query.answers.map((answer, i) => (
                                            <li key={i}>{answer}</li>
                                        ))}
                                    </ul>
                                </div>
                            )}
                        </div>
                    ))}
                </div>
            </div>
            <HomeFooter />
        </div>
    );
}

export default ATMBranchLocator;
